apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-deploy
spec:
  replicas: 10
  minReadySeconds: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  template:
    metadata:
      labels:
        app: hello-apache
        env: prod
        version: 1.0.1
    spec:
      containers:
      - name: hello-pod
        image: httpd:latest
        ports:
        - containerPort: 80
